>>> from astropy.io import fits
>>> hdus = fits.open('sample.fits')
>>> hdus[0].header
SIMPLE  =                    T / file c ...
BITPIX  =                   16 / number ...
NAXIS   =                    0 / number ...
EXTEND  =                    T / FITS d ...
...